[package]
name = "vr_device"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
autocxx = "0.30.0"
cxx = "1.0"
vulkano = "0.35.2"
vulkano-util = "0.35.0"
winit = "0.30"

[build-dependencies]
autocxx-build = "0.30.0"
miette = { version = "5", features = ["fancy"] }